version: '3.8'

services:
  db:
    # Menggunakan image PostgreSQL yang sudah terinstall pgvector
    image: ankane/pgvector:latest
    container_name: wisata_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wisata_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: wisata_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: wisata_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
